# Generated by Django 3.2 on 2023-06-18 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rgb_sensor',
            old_name='image',
            new_name='image_url',
        ),
    ]
