# Generated by Django 3.2 on 2023-06-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_image_rgb_sensor_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='collision_detector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='depth_camera_images')),
            ],
        ),
        migrations.CreateModel(
            name='depth_camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='depth_camera_images')),
            ],
        ),
        migrations.CreateModel(
            name='DVS_camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='depth_camera_images')),
            ],
        ),
        migrations.CreateModel(
            name='GNSS_sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='depth_camera_images')),
            ],
        ),
        migrations.CreateModel(
            name='IMU_sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='depth_camera_images')),
                ('accelerometer', models.IntegerField()),
                ('gyroscopeX', models.IntegerField()),
                ('gyroscopeY', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='instance_segmentation_camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='depth_camera_images')),
            ],
        ),
        migrations.CreateModel(
            name='lane_invasion_detector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='depth_camera_images')),
            ],
        ),
        migrations.CreateModel(
            name='lidar_sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='depth_camera_images')),
            ],
        ),
        migrations.CreateModel(
            name='obstacle_detector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='depth_camera_images')),
            ],
        ),
        migrations.CreateModel(
            name='optical_flow_camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='depth_camera_images')),
            ],
        ),
        migrations.CreateModel(
            name='radar_sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='depth_camera_images')),
            ],
        ),
        migrations.CreateModel(
            name='rss_sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='depth_camera_images')),
            ],
        ),
        migrations.CreateModel(
            name='semantic_lidar_sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='depth_camera_images')),
            ],
        ),
        migrations.CreateModel(
            name='semantic_segmentation_camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='semantic_segmentation_images')),
            ],
        ),
    ]
